version: '3'
services:
  tax:
    # deploy:
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    # networks:
    #   - webnet
    build: taxService
      #uncomment below to expose this service outside the container network

    # ports:
    #   - "3000:3000"
  cost:
    build: costService
    links:
      - "tax"
    environment:
      - TAX_SERVICE_URL=http://tax:8080
    ports:
      - "8080:8080"